config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :find_book, only: [:show, :edit, :update, :destroy]
	def index
		@books = Book.all.order("created_at DESC")
	end

	def show
	end

	def new
		@book = Book.new
	end

	def edit
	end

	def update
		if @book.update(book_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@book.destroy
		redirect_to root_path
	end

	def create
		@book = Book.new(book_params)

		if @book.save
			redirect_to root_path
		else 
			render 'new'
		end
	end

	private
		def book_params
			params.require(:book).permit(:title, :description, :author)
		end
		def find_book
			@book = Book.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h2> Edit Book </h2>

<%= render 'form' %>

app/views/books/index.html.erb
<% @books.each do |book| %>
	<h2><%= link_to book.title, book_path(book) %></h2>
<% end %> 

<%= link_to "Add Book", new_book_path %>

app/views/books/new.html.erb
<h1> New Book </h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h2> <%= @book.title %> </h2>
<h3> <%= @book.author %> </h3>
<p> <%= @book.description %> </p>
<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you Sure ?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>